# Generated by Django 3.0.4 on 2020-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Material',
            new_name='material',
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_amount',
            field=models.FloatField(),
        ),
    ]
