# Generated by Django 3.0.3 on 2020-03-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='received_amount',
            field=models.FloatField(default=0),
        ),
    ]
