# Generated by Django 3.0.3 on 2020-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorder',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
