# Generated by Django 3.0.3 on 2020-02-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Item',
        ),
    ]
