# Generated by Django 3.0.3 on 2020-03-08 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mixcredit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
