# Generated by Django 3.0 on 2020-03-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinework',
            name='average_feet',
        ),
    ]
