# Generated by Django 3.0.3 on 2020-03-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinework',
            name='average_feet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinework',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclework',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
