# Generated by Django 3.0.3 on 2020-03-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('staff', 'staff'), ('petrol', 'petrol'), ('food', 'food'), ('office_accesories', 'office_accesories'), ('other', 'other')], max_length=50)),
                ('debit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.MixDebit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Owner')),
            ],
        ),
    ]
