# Generated by Django 3.0.3 on 2020-02-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineparty',
            old_name='party_id',
            new_name='credit_id',
        ),
        migrations.RenameField(
            model_name='purchaseparty',
            old_name='party_id',
            new_name='credit_id',
        ),
        migrations.RenameField(
            model_name='vehicleparty',
            old_name='party_id',
            new_name='credit_id',
        ),
    ]
