# Generated by Django 3.0 on 2020-02-26 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixdebit',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
