# Generated by Django 3.0.3 on 2020-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200222_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinework',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiclework',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
