# Generated by Django 3.0 on 2020-02-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200226_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='debit_id',
        ),
    ]
