# Generated by Django 3.0.3 on 2020-03-08 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200308_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='village',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
