# Generated by Django 3.0.3 on 2020-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_dailywork_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixcredit',
            name='category',
            field=models.CharField(choices=[('machine_party', 'machine_party'), ('vehicle_party', 'vehicle_party'), ('daily_work', 'daily_work')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mixdebit',
            name='category',
            field=models.CharField(choices=[('part', 'part'), ('owner_debit', 'owner_debit'), ('purchase', 'purchase'), ('worker', 'worker'), ('daily_expense', 'daily_expense')], max_length=100, null=True),
        ),
    ]
