# Generated by Django 3.0 on 2020-02-26 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_purchase_debit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mixdebit',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
