# Generated by Django 3.0.3 on 2020-02-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200223_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinework',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiclework',
            name='date',
            field=models.DateField(),
        ),
    ]
