# Generated by Django 3.0.3 on 2020-02-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200223_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinework',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Machine'),
        ),
    ]
