# Generated by Django 3.0.4 on 2020-03-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200318_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixdebit',
            name='category',
            field=models.CharField(choices=[('part_debit', 'part_debit'), ('owner_debit', 'owner_debit'), ('purchase_debit', 'purchase_debit'), ('worker_debit', 'worker_debit'), ('daily_expense_debit', 'daily_expense_debit')], max_length=100, null=True),
        ),
    ]
