# Generated by Django 3.0 on 2020-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200226_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='advance',
        ),
        migrations.AlterField(
            model_name='worker',
            name='exit_date',
            field=models.DateField(blank=True),
        ),
    ]
