# Generated by Django 3.0 on 2020-02-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200226_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
