# Generated by Django 3.0.3 on 2020-02-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200223_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VeicleWorkVehicles',
            new_name='VehicleWorkVehicles',
        ),
    ]
