# Generated by Django 3.0.3 on 2020-02-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200226_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyExpense',
        ),
    ]
