# Generated by Django 3.0 on 2020-02-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200226_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Item')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.VehicleParty')),
            ],
        ),
        migrations.RenameModel(
            old_name='Supply',
            new_name='MachineSupply',
        ),
        migrations.AlterField(
            model_name='machinesupply',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.MachineParty'),
        ),
        migrations.DeleteModel(
            name='DailyExpense',
        ),
    ]
