# Generated by Django 3.0.3 on 2020-02-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_delete_dailyexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='diesel_spend',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='five_feet',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='five_feet_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='net_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='two_half_feet',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='two_half_feet_rate',
            field=models.FloatField(),
        ),
    ]
